version: "2.1"

services:
  adminMarketingUI:
    container_name: al_adminMarketingUI
    image: "al/fe/admin_marketing_ui"
    ports:
      - "8080:80"
    expose:
      - "8080"
    restart: always
    links:
      - dashboardService
  clientUI:
    container_name: al_clientUI
    image: "al/fe/client_ui"
    ports:
      - "8081:80"
    expose:
      - "8081"
    restart: always
    links:
      - dashboardService
  dashboardService:
    container_name: al_dashboardService
    image: "al/ws/dashboardservice"
    ports:
      - "9555:8080"
    expose:
      - "9555"
    restart: always
    links:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"

  influxdb:
    image: influxdb
    ports: 8086:8086
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"

# Add to containers talking to Kafka:
# links:
#     - kafka
#
# Test:
# docker-compose up
# docker exec -it <container_kafka_id> bash
# kafka-console-producer.sh --broker-list localhost:9092 --topic topic
# <Write some messages, then CTRL-C>
# kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic topic --from-beginning
# Your messages are being read WOW
