# J2E Composition
version: "2.1"

services:
  # Frontend
  # /marketingui/
  adminMarketingUI:
    container_name: fe_admin_marketing_ui
    image: "blablamove/fe-admin-marketing-ui"
    ports:
      - "4201:80"
    restart: always

  # /
  clientUI:
    container_name: fe_client_ui
    image: "blablamove/fe-client-ui"
    ports:
      - "4202:80"
    restart: always

  # Backend
  dashboardService:
    container_name: be_dashboard_service
    image: "blablamove/be-dashboard-service"
    ports:
      - "8080:8080"
    restart: always
    extra_hosts:
      - "kafka:10.132.0.2"
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb

  # TSDB
  influxdb:
    image: influxdb
    healthcheck:
      test: "curl -sL -I localhost:8086/ping | grep \"204 No Content\""
      interval: 3s
      retries: 2
    ports:
      - 8086:8086
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
