swagger: "2.0"
info:
    description: Core Delivery API
    version: 1.0.0
    title: Core Delivery API
    contact:
        email: nikita.rousseau@etu.unice.fr
    license:
        name: MIT
        url: https://opensource.org/licenses/MIT

host: 0.0.0.0:5000

tags:
    - name: delivery
      description: Delivery related calls

paths:
    /route:
        post:
            tags:
                - route
            operationId: newRoute
            description: Create a new route.
            consumes:
                - application/json
            produces:
                - application/json
            responses:
                200:
                    description: puts a new message on the 'route' topic
                    examples:
                        kafka message:
                            action: ROUTE_CREATED
                            message:
                                date: "2018-11-03 18:57:05.043943"
                                delivery_id: 493
    /delivery:
        post:
            tags:
                - delivery
            operationId: newDelivery
            description: Create a new delivery
            consumes:
                - application/json
            produces:
                - application/json
            responses:
                200:
                    description: puts a new message on 'delivery' topic
                    examples:
                        kafka message:
                            action: DELIVERY_INITIATED
                            message:
                                city: Indianapolis
                                date: "2018-11-03 18:57:05.043943"
                                delivery_id: 493
                                request: 265631681983298995857651895017366232219
    /delivery/checkpoint:
        post:
            tags:
                - delivery
            operationId: newDeliveryCheckpoint
            description: Notify that the delivery has reached a checkpoint
            consumes:
                - application/json
            produces:
                - application/json
            responses:
                200:
                    description: puts a new message on 'delivery' topic
                    examples:
                        kafka message:
                            action: DELIVERY_CHECKPOINT
                            message:
                                delivery_id: 1958
                                city: Detroit
                                date: "2018-11-03 19:13:37.374029"
                                isFinalDestination: true
                                request: 267632146774148875279637168125941151364

    /delivery/issue:
        post:
            tags:
                - delivery
            operationId: newDeliveryIssue
            description: Notify that a specific delivery has had an issue.
            consumes:
                - application/json
            produces:
                - application/json
            responses:
                200:
                    description: puts a new message on the 'delivery' topic
                    examples:
                        kafka message:
                            action: DELIVERY_ISSUE
                            message:
                                issue_type: DELIVERY_MISSING
