version: "2.1"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "topic:1:1,user:1:1,delivery:1:1,heartbeat:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
  influxdb:
    image: influxdb
    healthcheck:
      test: 'curl -sL -I localhost:8086/ping | grep "204 No Content"'
      interval: 3s
      retries: 2
    ports:
      - 8086:8086
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
# Add to containers talking to Kafka:
# links:
#     - kafka
#
# Test:
# docker-compose up
# docker exec -it <container_kafka_id> bash
# kafka-console-producer.sh --broker-list localhost:9092 --topic topic
# <Write some messages, then CTRL-C>
# kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic topic --from-beginning
# Your messages are being read WOW
