version: "2.1"

services:
  adminMarketingUI:
    container_name: fe_admin_marketing_ui
    image: "blablamove/fe-admin-marketing-ui"
    ports:
      - "4201:80"
    restart: always

  clientUI:
    container_name: fe_client_ui
    image: "blablamove/fe-client-ui"
    ports:
      - "4202:80"
    restart: always

  dashboardService:
    container_name: be_dashboard_service
    image: "blablamove/be-dashboard-service"
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      influxdb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    links:
      - kafka
      - influxdb

  kpi:
    container_name: core_kpi
    image: "blablamove/core-kpi"
    ports:
      - "5000:5000"
    depends_on:
      kafka:
        condition: service_healthy
    links:
      - kafka
    command: app.py production world

  user:
    container_name: core_user
    image: "blablamove/core-user"
    ports:
      - "5001:5000"
    depends_on:
      kafka:
        condition: service_healthy
    links:
      - kafka
    command: app.py production world

  delivery:
    container_name: core_delivery
    image: "blablamove/core-delivery"
    ports:
      - "5002:5000"
    depends_on:
      kafka:
        condition: service_healthy
    links:
      - kafka
    command: app.py production world

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "topic:1:1,user:1:1,delivery:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
    healthcheck:
        test: "kafka-topics.sh --zookeeper zk:2181 --list 2>&1 | grep \"delivery\""

  influxdb:
    image: influxdb
    healthcheck:
      test: "curl -sL -I localhost:8086/ping | grep \"204 No Content\""
      interval: 3s
      retries: 2
    ports:
      - 8086:8086
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"

# Add to containers talking to Kafka:
# links:
#     - kafka
#
# Test:
# docker-compose up
# docker exec -it <container_kafka_id> bash
# kafka-console-producer.sh --broker-list localhost:9092 --topic topic
# <Write some messages, then CTRL-C>
# kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic topic --from-beginning
# Your messages are being read WOW
